USE CompAccInc_DWGLENN

DROP TABLE IF EXISTS SalesFacts;
DROP TABLE IF EXISTS ContactDIM
DROP TABLE IF EXISTS CustomerDIM;
DROP TABLE IF EXISTS EmployeeDIM;
DROP TABLE IF EXISTS OrderDIM;
DROP TABLE IF EXISTS STOCKS;
DROP TABLE IF EXISTS ProductDIM;
DROP TABLE IF EXISTS ProductCategoryDIM;
DROP TABLE IF EXISTS TimeDIM;
