USE CompAccInc_OLTPGLENN;

CREATE TABLE CUSTOMERS 
(CUSTOMER_ID INT NOT NULL PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
ADDRESS VARCHAR(255) NOT NULL,
WEBSITE VARCHAR(100) NOT NULL,
CREDIT_LIMIT DECIMAL(10,2) NOT NULL)

CREATE TABLE CONTACTS
(CONTACT_ID INT NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PHONE VARCHAR(20) NOT NULL,
CUSTOMER_ID INT NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID))

CREATE TABLE EMPLOYEES
(EMPLOYEE_ID INT NOT NULL,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL, 
EMAIL VARCHAR(100) NOT NULL,
PHONE VARCHAR(20) NOT NULL,
HIRE_DATE DATETIME NOT NULL,
MANAGER_ID INT,
JOB_TITLE VARCHAR(100) NOT NULL,
PRIMARY KEY (EMPLOYEE_ID), 
CONSTRAINT FK_MANGER_EMPLOYEES
FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID))

CREATE TABLE ORDERS
(ORDER_ID INT NOT NULL PRIMARY KEY,
CUSTOMER_ID INT NOT NULL,
STATUS VARCHAR(10) NOT NULL,
SALESMAN_ID INT NOT NULL,
ORDER_DATE DATETIME NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
FOREIGN KEY (SALESMAN_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID))

CREATE TABLE PRODUCT_CATEGORIES
(CATEGORY_ID INT NOT NULL,
CATEGORY_NAME VARCHAR(20) NOT NULL,
PRIMARY KEY (CATEGORY_ID))

CREATE TABLE PRODUCTS
(PRODUCT_ID INT NOT NULL PRIMARY KEY,
PRODUCT_NAME VARCHAR(100) NOT NULL,
DESCRIPTION VARCHAR(200) NOT NULL,
STANDARD_COST DECIMAL(10,2) NOT NULL,
LIST_PRICE DECIMAL(10,2) NOT NULL,
CATEGORY_ID INT NOT NULL,
FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCT_CATEGORIES(CATEGORY_ID))

CREATE TABLE ORDER_ITEMS 
(ORDER_ID INT NOT NULL,
ITEM_ID INT NOT NULL,
PRODUCT_ID INT NOT NULL,
QUANTITY INT NOT NULL,
UNIT_PRICE DECIMAL(10,2) NOT NULL
PRIMARY KEY(ORDER_ID, ITEM_ID),
FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID))

CREATE TABLE REGIONS
(REGION_ID INT NOT NULL PRIMARY KEY,
REGION_NAME VARCHAR(100) NOT NULL)

CREATE TABLE COUNTRIES
(COUNTRY_ID CHAR(2) NOT NULL PRIMARY KEY,
COUNTRY_NAME VARCHAR(100) NOT NULL,
REGION_ID INT NOT NULL,
FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID))

CREATE TABLE LOCATIONS
(LOCATION_ID INT NOT NULL PRIMARY KEY,
ADDRESS VARCHAR(255) NOT NULL,
POSTAL_CODE VARCHAR(50) Null,
CITY VARCHAR(100) NOT NULL,
STATE VARCHAR(255) Null,
COUNTRY_ID CHAR(2) NOT NULL,
FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID))

CREATE TABLE WAREHOUSES
(WAREHOUSE_ID INT NOT NULL PRIMARY KEY,
WAREHOUSE_NAME VARCHAR(100) NOT NULL,
LOCATION_ID INT NOT NULL,
FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID))

CREATE TABLE INVENTORIES
(PRODUCT_ID INT NOT NULL,
WAREHOUSE_ID INT NOT NULL,
QUANTITY INT NOT NULL,
PRIMARY KEY (PRODUCT_ID, WAREHOUSE_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID))