USE CompAccInc_DWGLENN

-- Customer

INSERT INTO 
	CustomerDIM(CUSTOMER_ID, NAME, ADDRESS, WEBSITE, CREDIT_LIMIT)
SELECT
	cs.CUSTOMER_ID, cs.NAME, cs.ADDRESS, cs.WEBSITE, cs.CREDIT_LIMIT
FROM
	CompAccInc_OLTPGLENN..CUSTOMERS cs

-- Contact

INSERT INTO 
	ContactDIM(CONTACT_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, CUSTOMER_ID)
SELECT
	cn.CONTACT_ID, cn.FIRST_NAME, cn.LAST_NAME, cn.EMAIL, cn.PHONE, cn.CUSTOMER_ID
FROM
	CompAccInc_OLTPGLENN..CONTACTS cn

-- Employees

INSERT INTO
	EmployeeDIM(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, HIRE_DATE, MANAGER_ID, JOB_TITLE)
SELECT
	EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, HIRE_DATE, MANAGER_ID, JOB_TITLE
FROM 
	CompAccInc_OLTPGLENN..EMPLOYEES

-- Orders

INSERT INTO
	OrderDIM(ORDER_ID, STATUS)
SELECT
	ORDER_ID, STATUS
FROM
	CompAccInc_OLTPGLENN..ORDERS

-- Product Categories

CREATE TABLE STOCKS
(PRODUCT_ID INT PRIMARY KEY,
STOCK int)

INSERT INTO
	STOCKS(PRODUCT_ID, STOCK)
SELECT 
	PRODUCT_ID, SUM(QUANTITY)
FROM 
	CompAccInc_OLTPGLENN..INVENTORIES
GROUP BY
	PRODUCT_ID

INSERT INTO
	ProductCategoryDIM(CATEGORY_ID, CATEGORY_NAME)
SELECT 
	CATEGORY_ID, CATEGORY_NAME
FROM
	CompAccInc_OLTPGLENN..PRODUCT_CATEGORIES

-- Products

INSERT INTO
	ProductDIM(PRODUCT_ID, QUANTITY, PRODUCT_NAME, DESCRIPTION, CATEGORY_ID)
SELECT
	p.PRODUCT_ID, s.STOCK, p.PRODUCT_NAME, p.DESCRIPTION, p.CATEGORY_ID
FROM
	CompAccInc_OLTPGLENN..PRODUCTS p 
	LEFT JOIN STOCKS s ON p.PRODUCT_ID = s.PRODUCT_ID

-- Time

DECLARE @StartDate DATETIME = '20130601' --Starting value of Date Range
DECLARE @EndDate DATETIME = '20300101' --End Value of Date Range

WHILE @StartDate <= @EndDate         
BEGIN
    DECLARE @YearMonthDay VARCHAR(8) = CONVERT(VARCHAR(8), @StartDate, 112); -- 112 corresponds to yyyymmdd (ISO format)
    DECLARE @Month INT = MONTH(@StartDate);

    INSERT INTO TimeDIM (time_id, Date, DayOfWeek, DayOfMonth, Month, Quarter, Year)
    VALUES (
        @YearMonthDay,
        @StartDate,
        DATEPART(WEEKDAY, @StartDate),
        DAY(@StartDate),
        @Month,
        CAST(DATEPART(QUARTER, @StartDate) AS VARCHAR),
        YEAR(@StartDate)
    );

    SET @StartDate = DATEADD(DAY, 1, @StartDate);
END;

-- SalesFacts

USE CompAccInc_DWGLENN

DELETE FROM SalesFacts

INSERT INTO CompAccInc_DWGLENN..SalesFacts
(TIME_ID,PRODUCT_ID,ORDER_ID,EMPLOYEE_ID,CUSTOMER_ID,ITEM_ID,QUANTITY,UNIT_PRICE,LIST_PRICE,STANDARD_COST)

SELECT
	replace(CONVERT(DATE,o.ORDER_DATE, 112),'-',''),
	p.PRODUCT_ID,
	o.ORDER_ID,
	e.EMPLOYEE_ID,
	c.CUSTOMER_ID,
	oi.ITEM_ID,
	oi.QUANTITY,
	oi.UNIT_PRICE,
	p.LIST_PRICE,
	p.STANDARD_COST

FROM
CompAccInc_OLTPGLENN..ORDERS o, 
CompAccInc_OLTPGLENN..PRODUCTS p, 
CompAccInc_OLTPGLENN..EMPLOYEES e,
CompAccInc_OLTPGLENN..CUSTOMERS c, 
CompAccInc_OLTPGLENN.. ORDER_ITEMS oi,

CompAccInc_DWGLENN..OrderDIM od,
CompAccInc_DWGLENN..ProductDIM pd,
CompAccInc_DWGLENN..CustomerDIM cd,
CompAccInc_DWGLENN..EmployeeDIM ed

WHERE 
o.ORDER_ID = od.ORDER_ID AND
p.PRODUCT_ID = pd.PRODUCT_ID AND
c.CUSTOMER_ID = cd.CUSTOMER_ID AND
e.EMPLOYEE_ID = ed.EMPLOYEE_ID AND
oi.ORDER_ID = od.ORDER_ID AND
oi.PRODUCT_ID = pd.PRODUCT_ID AND
o.SALESMAN_ID = e.EMPLOYEE_ID AND

o.SALESMAN_ID = e.EMPLOYEE_ID AND
o.ORDER_ID = oi.ORDER_ID AND
oi.PRODUCT_ID = p.PRODUCT_ID AND
c.CUSTOMER_ID = o.CUSTOMER_ID 