USE CompAccInc_OLTPGLENN;

DROP TABLE IF EXISTS INVENTORIES;
DROP TABLE IF EXISTS WAREHOUSES;
DROP TABLE IF EXISTS LOCATIONS;
DROP TABLE IF EXISTS COUNTRIES;
DROP TABLE IF EXISTS REGIONS;
DROP TABLE IF EXISTS ORDER_ITEMS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS PRODUCT_CATEGORIES;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS CONTACTS;
DROP TABLE IF EXISTS CUSTOMERS;